import React from 'react';
import { Scale, ArrowLeft, ShieldAlert, CheckCircle2 } from 'lucide-react';
import { useAppRouter } from '../context/RouterContext';
import { TrademarkDisclaimer } from '../components/TrademarkDisclaimer';

export const TermsPage: React.FC = () => {
  const { navigate } = useAppRouter();

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8 font-sans">
      <button
        onClick={() => navigate('/')}
        className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-800 transition-colors cursor-pointer"
      >
        <ArrowLeft className="w-4 h-4" />
        <span>Return to Diagnostic Hub</span>
      </button>

      <header className="border-b border-slate-200 pb-6 space-y-3">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-100 border border-slate-200 text-slate-800 text-xs font-bold">
          <Scale className="w-3.5 h-3.5 text-slate-600" />
          <span>Legal Usage Agreement & Liability Disclaimers</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight font-['Google_Sans',sans-serif]">
          Terms of Service & Usage Agreement
        </h1>
        <p className="text-sm text-slate-500">
          Last Updated: October 2026 • Canonical URL: https://gladsenseedu.com/terms/
        </p>
      </header>

      <TrademarkDisclaimer />

      <main className="space-y-6 text-sm text-slate-700 leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">1. Acceptance of Terms</h2>
          <p>
            By accessing or using GladSense (accessible via https://gladsenseedu.com and affiliated subdomains), you agree to be bound by these Terms of Service. If you do not agree to all terms and conditions, you must discontinue use of the tools and services immediately.
          </p>
        </section>

        <section className="space-y-3 p-5 rounded-2xl bg-amber-50/70 border border-amber-200">
          <h2 className="text-lg font-bold text-amber-950 flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-amber-600" />
            <span>2. Strict Non-Guarantee of Third-Party Ad Approvals</span>
          </h2>
          <p className="text-amber-900">
            <strong>CRITICAL LEGAL NOTICE:</strong> GladSense is an independent educational diagnostic suite designed to help webmasters audit their technical infrastructure against published industry standards. <strong>GladSense does NOT guarantee, warrant, or promise that your website will receive approval from Google AdSense, Alphabet Inc., or any third-party advertising exchange.</strong>
          </p>
          <p className="text-amber-900 text-xs">
            Final approval or rejection decisions rest exclusively with Google LLC and its independent human quality evaluators. Applying GladSense recommendations, code fixes, and SOP blueprints improves compliance probability but does not constitute a legally binding approval warranty.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">3. Permitted & Acceptable Diagnostic Use</h2>
          <p>
            You agree to use our automated Site Doctor and KGR keyword scanners solely to audit websites that you own, operate, or have explicit authorization to inspect. You agree not to:
          </p>
          <ul className="list-disc list-inside space-y-1 text-xs text-slate-600 pl-2">
            <li>Launch distributed Denial of Service (DDoS) requests against external domains through our scanner proxy.</li>
            <li>Use the platform to audit domains containing illegal, malicious, defamatory, or copyright-infringing content.</li>
            <li>Circumvent rate limits or programmatically abuse backend diagnostic endpoints.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900">4. Revenue Modeling & Financial Estimates</h2>
          <p>
            All revenue projections, Page RPM estimates, and financial simulations generated by the GladSense Revenue Planner are for educational and planning scenarios only. Actual advertising yield is determined by auction dynamics, advertiser budgets, visitor geolocation, and ad viewability physics. GladSense assumes no liability for revenue shortfalls or financial decisions made based on tool calculations.
          </p>
        </section>

        <section className="space-y-3 border-t border-slate-200 pt-4">
          <h2 className="text-lg font-bold text-slate-900">5. Governing Law & Contact</h2>
          <p>
            These Terms are governed by applicable legal codes. Inquiries regarding this agreement may be submitted to <a href="mailto:compliance@gladsenseedu.com" className="text-[#1a73e8] underline">compliance@gladsenseedu.com</a>.
          </p>
        </section>
      </main>
    </div>
  );
};
